### ISSUE TITLE
Non user-friendly error when review comment is too large

### ISSUE THREAD

**Issue by ruthsykes** [world-class/compass#46]
Nasty raw JS error when review text is too large (afraid I didn't note how many characters it was, I just pasted a lot). Suggest a more user-friendly error, or some validation:

PayloadTooLargeError: request entity too large
    at readStream (/home/ubuntu/compass/node_modules/raw-body/index.js:155:17)
    at getRawBody (/home/ubuntu/compass/node_modules/raw-body/index.js:108:12)
    at read (/home/ubuntu/compass/node_modules/body-parser/lib/read.js:77:3)
    at urlencodedParser (/home/ubuntu/compass/node_modules/body-parser/lib/types/urlencoded.js:116:5)
    at Layer.handle [as handle_request] (/home/ubuntu/compass/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/compass/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/compass/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/compass/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/compass/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/ubuntu/compass/node_modules/serve-static/index.js:75:16)

**Comment by amenat** [comment]
Thanks @ruthsykes for report

TODO:
- [ ] limit max. characters in review both client/server side.
- [ ] show 500 error and disable debug messages.

**Comment by BlairCurrey** [comment]
max length is set to 8000 in `addreview.html`, `editreview.html` and in `validateReview()` in `routes/main.js`
